### ISSUE TITLE
How to use this model on Tiny ImageNet for classification

### ISSUE THREAD

**Issue by tngok-wustl** [pranavphoenix/WaveMix#6]
I am a computer visions student who is thinking about using your WaveMix model for my final project. I am planning to use it on the Tiny ImageNet dataset for classification and model evaluation. However, I have to run all my deep learning code on Google Colab, since I do not have an independent and powerful GPU.

So, I have a few questions regarding using the model:

1. How can I load the Tiny ImageNet dataset in Google Colab? Can you give a python code for it?
2. The Readme said that WaveMix reduces the use of GPU resources. Is my T4 GPU on Google Colab enough for training the Tiny ImageNet?
3. Where is the code for Tiny ImageNet classification? Is there a pre-trained model for it?
4. In case I want to retrain the model, where is the code for training the model?

**Comment by pranavphoenix** [comment]
1. I have a repository called tinyimagenet dataloader which will work in colab.
2.  Yes
3. Yes, the pre-trained weights are available in https://github.com/pranavphoenix/WaveMix/tree/main/Saved_weights/tinyimagenet
4. https://github.com/pranavphoenix/WaveMix/blob/main/Image_Classification/tinyimagenet.py
